package com.diary.moonpage.core.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.res.stringResource
import com.diary.moonpage.R

@Composable
@ReadOnlyComposable
fun getTranslatedActivityName(name: String): String {
    return when (name) {
        "Alcohol" -> stringResource(R.string.activity_name_alcohol)
        "Angry" -> stringResource(R.string.activity_name_angry)
        "Anniversary" -> stringResource(R.string.activity_name_anniversary)
        "Annoyed" -> stringResource(R.string.activity_name_annoyed)
        "Anxious" -> stringResource(R.string.activity_name_anxious)
        "Beverage" -> stringResource(R.string.activity_name_beverage)
        "Bored" -> stringResource(R.string.activity_name_bored)
        "Breakfast" -> stringResource(R.string.activity_name_breakfast)
        "Brush Teeth" -> stringResource(R.string.activity_name_brush_teeth)
        "Cafe" -> stringResource(R.string.activity_name_cafe)
        "Calm" -> stringResource(R.string.activity_name_calm)
        "Checkup" -> stringResource(R.string.activity_name_checkup)
        "Cinema" -> stringResource(R.string.activity_name_cinema)
        "Class" -> stringResource(R.string.activity_name_class)
        "Cleaning" -> stringResource(R.string.activity_name_cleaning)
        "Cloudy" -> stringResource(R.string.activity_name_cloudy)
        "Coffee" -> stringResource(R.string.activity_name_coffee)
        "Cold" -> stringResource(R.string.activity_name_cold)
        "Conflict" -> stringResource(R.string.activity_name_conflict)
        "Cooking" -> stringResource(R.string.activity_name_cooking)
        "Date" -> stringResource(R.string.activity_name_date)
        "Depressed" -> stringResource(R.string.activity_name_depressed)
        "Dinner" -> stringResource(R.string.activity_name_dinner)
        "Dishes" -> stringResource(R.string.activity_name_dishes)
        "Drawing" -> stringResource(R.string.activity_name_drawing)
        "Drink Water" -> stringResource(R.string.activity_name_drink_water)
        "End on Time" -> stringResource(R.string.activity_name_end_on_time)
        "Enthusiastic" -> stringResource(R.string.activity_name_enthusiastic)
        "Exam" -> stringResource(R.string.activity_name_exam)
        "Excited" -> stringResource(R.string.activity_name_excited)
        "Exercise" -> stringResource(R.string.activity_name_exercise)
        "Family" -> stringResource(R.string.activity_name_family)
        "Friends" -> stringResource(R.string.activity_name_friends)
        "Gaming" -> stringResource(R.string.activity_name_gaming)
        "Gift" -> stringResource(R.string.activity_name_gift)
        "Grateful" -> stringResource(R.string.activity_name_grateful)
        "Hair" -> stringResource(R.string.activity_name_hair)
        "Happy" -> stringResource(R.string.activity_name_happy)
        "Homework" -> stringResource(R.string.activity_name_homework)
        "Hopeful" -> stringResource(R.string.activity_name_hopeful)
        "Hospital" -> stringResource(R.string.activity_name_hospital)
        "Hot" -> stringResource(R.string.activity_name_hot)
        "Laundry" -> stringResource(R.string.activity_name_laundry)
        "Lonely" -> stringResource(R.string.activity_name_lonely)
        "Lunch" -> stringResource(R.string.activity_name_lunch)
        "Makeup" -> stringResource(R.string.activity_name_makeup)
        "Medicine" -> stringResource(R.string.activity_name_medicine)
        "Movie" -> stringResource(R.string.activity_name_movie)
        "Music" -> stringResource(R.string.activity_name_music)
        "Nails" -> stringResource(R.string.activity_name_nails)
        "Night Snack" -> stringResource(R.string.activity_name_night_snack)
        "None" -> stringResource(R.string.activity_name_none)
        "Overtime" -> stringResource(R.string.activity_name_overtime)
        "Partner" -> stringResource(R.string.activity_name_partner)
        "Party" -> stringResource(R.string.activity_name_party)
        "Pit-a-pat" -> stringResource(R.string.activity_name_pit_a_pat)
        "Pressured" -> stringResource(R.string.activity_name_pressured)
        "Proud" -> stringResource(R.string.activity_name_proud)
        "Rainy" -> stringResource(R.string.activity_name_rainy)
        "Reading" -> stringResource(R.string.activity_name_reading)
        "Refreshed" -> stringResource(R.string.activity_name_refreshed)
        "Relaxed" -> stringResource(R.string.activity_name_relaxed)
        "Restaurant" -> stringResource(R.string.activity_name_restaurant)
        "Sad" -> stringResource(R.string.activity_name_sad)
        "School" -> stringResource(R.string.activity_name_school)
        "Sex" -> stringResource(R.string.activity_name_sex)
        "Shopping" -> stringResource(R.string.activity_name_shopping)
        "Shower" -> stringResource(R.string.activity_name_shower)
        "Sick" -> stringResource(R.string.activity_name_sick)
        "Skincare" -> stringResource(R.string.activity_name_skincare)
        "Smoking" -> stringResource(R.string.activity_name_smoking)
        "Snack" -> stringResource(R.string.activity_name_snack)
        "Snowy" -> stringResource(R.string.activity_name_snowy)
        "Stay Home" -> stringResource(R.string.activity_name_stay_home)
        "Stormy" -> stringResource(R.string.activity_name_stormy)
        "Stressed" -> stringResource(R.string.activity_name_stressed)
        "Study" -> stringResource(R.string.activity_name_study)
        "Sunny" -> stringResource(R.string.activity_name_sunny)
        "TV & Content" -> stringResource(R.string.activity_name_tv_content)
        "Tea" -> stringResource(R.string.activity_name_tea)
        "Tired" -> stringResource(R.string.activity_name_tired)
        "Travel" -> stringResource(R.string.activity_name_travel)
        "Vacation" -> stringResource(R.string.activity_name_vacation)
        "Walk" -> stringResource(R.string.activity_name_walk)
        "Wash Face" -> stringResource(R.string.activity_name_wash_face)
        "Windy" -> stringResource(R.string.activity_name_windy)
        "Work" -> stringResource(R.string.activity_name_work)
        else -> name
    }
}
